bakery.translation={                
		"shopType" :"Shop Type",
		"location":"Location",
		"staff":"Staff",
		"Exp":"Expenditures",
		"inventory":"Inventory",
		"brkEven":"Break Even",
		"accounting":"Accounting",
		"welcome":"Welcome!",
		"getStarted1":"Let's get you started with",
		"getStarted2":"building your new shop.",
		"shopName":"Shop</br> Name",
		"cafe":"Cafe",
		"bakery":"Bakery",
		"picLocation":"Pick a location",
		"locMarina":"Marina Bay Link Mall",		
		"locBugis" : "Bugis Junction",
		"locSerangoon" : "Nex",
		"hireAStaff" : "Hire a Staff",
		"hireQtyStaff" : "Hire",
		"mnthlyRental" : "Monthly Rental",
		"mnthlyUtility" : "Monthly Utility Bills",
		"mnthlySalary" : "Monthly Salary",
		"mnthlyFixed" : "Calculate Monthly Fixed Expenses",
		"pMgrDiv": "First Manager",
		"sMgrDiv": "Second Manager",
		"mnthlyFixedExp": "Calculate Monthly Fixed Expenses",
		"exp1":"Now, try calculating your Monthly Fixed Expenses below.",
		"calcTxt":"Need a calculator?",
		"exp2":"Your Selections were:",
		"contributionmargin1":"Let's calculate your contribution margin per unit",
		"sellingPrice":"Selling Price",
		"variableExp":"Variable Expense for One Unit",
		"contriMargin":"Contribution Margin",		
		"brkEven1":"Let's find out how many units you have to sell in order to Break Even",
		"totalFxdExp":"Total Monthly Fixed Expenses",
		"brkEvenUnit":"Break Even Unit",
		
		
    }

